#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
# -----------------------------------------------------------------------------

if [ ! -f /data/minecraft_server.jar ]
then
    curl "https://launcher.mojang.com/v1/objects/a412fd69db1f81db3f511c1463fd304675244077/server.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -Xmx2G -jar minecraft_server.jar nogui
